#AutoAudit Compliance Violation Alerts - Prometheus Alerting Rules
#File: compliance_alerts.yaml
#Location: /infrastructure/monitoring/alerts/
#Description: Defines high and medium severity compliance violation alerts.
#Author: Senior Lead, AutoAudit DevSecOps Team
#Last Updated: 2025-09-17

groups:
- name: compliance.rules
  interval: 1m
  rules:

  - alert: MissingComplianceScans
    
    expr: |
      absent_over_time(compliance_scan_success[1h])
    
    for: 10m
    
    labels:
      severity: high
      team: compliance
      service: compliance-scanner
      environment: production
    
    annotations:
      
      summary: "High: Compliance scans missing for over 1 hour"
      
      description: |
        No successful compliance scans have been recorded in the last hour.
        This may indicate scanner downtime or connectivity issues.
        An immediate investigation is required to ensure compliance posture.
      runbook: "https://github.com/Hardhat-Enterprises/AutoAudit/blob/main/infrastructure/monitoring/alerts/runbooks/RUNBOOKS.md#compliancemissingcompliancescans"

  - alert: FailedAuditChecks
    
    expr: |
      increase(compliance_audit_failures_total[30m]) > 5
    
    for: 15m
    
    labels:
      severity: high
      team: compliance
      service: audit-engine
      environment: production
    
    annotations:
      
      summary: "High: Multiple failed compliance audit checks"
      
      description: |
        More than five compliance audit failures were detected in the last 30 minutes.
        Review audit logs and promptly remediate non-compliant configurations.
      runbook: "https://github.com/Hardhat-Enterprises/AutoAudit/blob/main/infrastructure/monitoring/alerts/runbooks/RUNBOOKS.md#compliancefailedauditchecks"

  - alert: MissingControlsDetected
    
    expr: |
      compliance_missing_controls_total > 0
    
    for: 5m
    
    labels:
      severity: medium
      team: compliance
      service: control-monitor
      environment: production
    
    annotations:
    
      summary: "Medium: Missing compliance controls detected"
      
      description: |
        One or more required compliance controls are missing or disabled.
        Assess the impact and implement the missing controls to maintain compliance.
      runbook: "https://github.com/Hardhat-Enterprises/AutoAudit/blob/main/infrastructure/monitoring/alerts/runbooks/RUNBOOKS.md#compliancemissingcontrolsdetected"
