{{- if .Values.powershellService.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "autoaudit.fullname" . }}-powershell-service
  labels:
    {{- include "autoaudit.componentLabels" (dict "context" . "component" "powershell-service") | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "autoaudit.fullname" . }}-powershell-service
  minReplicas: {{ .Values.powershellService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.powershellService.autoscaling.maxReplicas }}
  metrics:
    {{- with .Values.powershellService.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ . }}
    {{- end }}
    {{- with .Values.powershellService.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ . }}
    {{- end }}
{{- end }}
