apiVersion: v1
kind: Service
metadata:
  name: {{ include "autoaudit.fullname" . }}-backend-api
  labels:
    {{- include "autoaudit.componentLabels" (dict "context" . "component" "backend-api") | nindent 4 }}
spec:
  type: {{ .Values.backendApi.service.type }}
  ports:
    - name: http
      port: {{ .Values.backendApi.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "autoaudit.selectorLabels" (dict "context" . "component" "backend-api") | nindent 4 }}
