apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-worker
  namespace: production
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: engine-worker
  template:
    metadata:
      labels:
        app: engine-worker
    spec:
      serviceAccountName: autoaudit
      containers:
        - name: engine-worker
          image: "{{ .Values.global.imageRegistry }}/engine-worker:{{ .Values.global.imageTag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          envFrom:
            - secretRef:
                name: autoaudit-app-secrets
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2
          args:
            - "--structured-logs"
            - "--port=5432"
            - "{{ .Values.global.cloudSqlInstance }}"
          securityContext:
            runAsNonRoot: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
