{{- if .Values.redis.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "autoaudit.fullname" . }}-redis
  labels:
    {{- include "autoaudit.componentLabels" (dict "context" . "component" "redis") | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.redis.persistence.storageClass }}
  storageClassName: {{ .Values.redis.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.redis.persistence.size | quote }}
{{- end }}
