name: "Cleanup Old Workflows (Dry Run)"

on:
  schedule:
    - cron: "0 0 * * 0"   # Every Sunday at midnight UTC
  workflow_dispatch:       # Manual trigger from Actions tab

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run cleanup script (dry run)
        run: npm run cleanup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
