name: "Security CI/CD"

on:
  push:
    branches: ['main', 'staging', 'dev']
  pull_request:
    branches: ['main', 'staging', 'dev']
  schedule:
    - cron: '32 23 * * 6'

jobs:
  changes:
    name: Allocating Push Filter
    runs-on: ubuntu-latest
    if: github.event_name == 'push' 
    permissions:
      pull-requests: read
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            security:
              - 'security/**'
          base: ${{ github.ref }} 
          # Detect changes against the most recent commit on the same branch

  analyze:
    name: Security Analysis on (${{ matrix.language }})
    needs: changes
    if: github.event_name != 'push' || needs.changes.outputs.security == 'true'  
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript-typescript' ]
        # 'actions'  'c-cpp' 'csharp', 'go', 'java-kotlin', 'javascript-typescript', 'python', 'ruby', 'rust', 'swift'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        build-mode: ${{ matrix.build-mode }}

    - if: matrix.build-mode == 'manual'
      shell: bash
      run: |
        echo 'If you are using a "manual" build mode for one or more of the' \
          'languages you are analyzing, replace this with the commands to build' \
          'your code, for example:'
        echo '  make bootstrap'
        echo '  make release'
        exit 1

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"
    
  run-lint:
    name: Linting Code
    runs-on: ubuntu-latest
    needs: [changes, analyze]
    if: github.event_name != 'push' || needs.changes.outputs.security == 'true'  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_YAML: false
          VALIDATE_GITHUB_ACTIONS: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_HTML: false

##  build-and-deploy:
#    name: Build and Deploy Backend
#   needs: [changes, analyze, run-lint]
#    environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}
#
#    runs-on: ubuntu-latest

#    steps:
#      - name: Checkout Source Code
#        uses: actions/checkout@v4
#        with:
#          ref: ${{ github.ref }}

#      - name: Set Environment
#        id: set-env
#        run: |
#          if [ "${{ github.ref_name }}" == "main" ]; then
#            echo "ENV_NAME=prod" >> $GITHUB_OUTPUT
#          else
#            echo "ENV_NAME=${{ github.ref_name }}" >> $GITHUB_OUTPUT
#          fi
#
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Build and tag Docker image
#        run: |
#          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:${{ steps.set-env.outputs.ENV_NAME }} \
#            --build-arg ENV=${{ steps.set-env.outputs.ENV_NAME }} \
#            -f backend/docker/backend.Dockerfile .
#
#      - name: Push Docker image
#        run: |
#          docker push ${{ secrets.DOCKER_USERNAME }}/backend:${{ steps.set-env.outputs.ENV_NAME }}
